### ISSUE TITLE
Makelogs doesn't work without --host set from the CLI

### ISSUE THREAD

**Issue by simianhacker** [kreeware/makelogs#7]
When I run makelogs without --host localhost:9200 set it throws an error when splitting by :

![image](https://cloud.githubusercontent.com/assets/41702/5730141/07a61fcc-9b35-11e4-949d-08bcac392051.png)

**Comment by chtitux** [comment]
I believe it is fixed in commit 3a08c7efd90a22738d33740e5035d743c7659ccf
